services:

#FRONT DE LA APLICACION
  kuenteco-ui:
    image: yefff/image-frontend-kuenteco-ui:1.0.9
    container_name: KuentecoUi
    ports:
      - "80:80"
    depends_on:
      - kuenteco-app
      - kuenteco-chat
    networks:
      - kuenteco-network
    restart: unless-stopped

# API KUENTECO-APP DEL BACKEND DE LA APLICACION
  kuenteco-app:
    image: yefff/image-backend-kuenteco-app:1.0.7
    container_name: KuentecoApp
    volumes:
      - ./BACK-END/KuentecoApp/.env.docker:/workspace/.env
    env_file:
      - ./BACK-END/KuentecoApp/.env.docker
    ports:
      - "8080:8080"
    depends_on:
      postgres-master-database:
        condition: service_healthy
      postgres-replica-database:
        condition: service_healthy
    networks:
      - kuenteco-network
    restart: unless-stopped

#BASE DE DATOS POSTGRESQL MAESTRA :D
  postgres-master-database:
    image: yefff/image-master-kuenteco:1.1.1
    container_name: DatabaseMasterKuenteCO
    volumes:
      - postgres-master-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - kuenteco-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U replicator -d KuenteCO|| exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 250s
    restart: unless-stopped

#BASE DE DATOS POSTGRESQL REPLICA :D
  postgres-replica-database:
    image: yefff/image-slave-kuenteco:1.1.2
    container_name: DatabaseSlaveKuenteCO
    volumes:
      - postgres-replica-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - kuenteco-network
    depends_on:
      postgres-master-database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U replicator -d KuenteCO|| exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 250s
    restart: unless-stopped

# API KUENTECO-CHAT DEL BACKEND DE LA APLICACION :D
  kuenteco-chat:
    image: yefff/image-backend-kuenteco-chat:1.0.8
    container_name: KuentecoChat
    volumes:
      - ./BACK-END/KuentecoChat/.env.docker:/workspace/.env
    env_file:
      - ./BACK-END/KuentecoChat/.env.docker
    ports:
      - "7070:7070"
    depends_on:
      mongo-database:
        condition: service_healthy
    networks:
      - kuenteco-network
    restart: unless-stopped

# BASE DE DATOS MONGODB :D
  mongo-database:
    image: yefff/image-mongo-kuenteco:1.0.0
    container_name: MongoDatabase
    volumes:
      - mongo-kuenteco-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - kuenteco-network
    command: ["mongod", "--bind_ip_all"]
    restart: unless-stopped


volumes:
  postgres-master-data:
  postgres-replica-data:
  mongo-kuenteco-data:
networks:
  kuenteco-network:
    driver: bridge
