apiVersion: v1
kind: Secret
metadata:
  name: kuenteco-secret
type: Opaque
data:
  SENDGRID_API_KEY: U0cueEZLSWI1RS1TRWFFRnFjN2ZuWkpIdy5HR3B6TFRDenI3NHBFckVaSk5jTDFLaVZ6cnNjTlNRV0x3enBBMkFCWjhz
  EMAIL_SENDGRID: YWxlamFuZHJvbW9saW5hYWNvc3RhMTFAZ21haWwuY29t
  VERIFICATION_EMAIL: ZC0wODk3ZWJjYzdmODE0ZTU2YjVhMTc5NDg3NDE0MWI0ZQ==
  RESET_PASSWORD: ZC02MjY5YWIwZGNhMTM0YWZlYjNkYjMzMDBlMzUxMGI0Yw==
  CLOUDINARY_NAME: ZHQ5dzBnZ3l3
  CLOUDINARY_API_KEY: ODU4ODgyNTc3MzE4Nzkx
  CLOUDINARY_API_SECRET: eXVobzRQX0pTVHlYQU50MV92R0kxZnJWVVpv
  BANCOLOMBIA_BASE_URL: aHR0cHM6Ly9ndy1zYW5kYm94LXFhLmFwcHMuYW1iaWVudGVzYmMuY29t
  BANCOLOMBIA_CLIENT_ID: ZDk2NWZkY2YzYWY1ODQ4NTY3ODZjNjY1MWMwZTI1YzE=
  BANCOLOMBIA_CLIENT_SECRET: NDgyZjMyNTBhMDlhNmNiNWE2MzRhYzZmOTg0OTk4MmQ=
  MERCADOPAGO_PUBLIC_KEY: VEVTVC1jZDc5NDY1ZC1hNGU1LTQ5OGUtYjBiYS0xZmFmMmNkYmMwZDc=
  MERCADOPAGO_ACCESS_TOKEN: VEVTVC03NjczOTM3Nzc5MjY2OTEzLTA3MDMxNi0xYjE0Mzc2ZjlhNTAxNDhmMzhjOTA2ZmI4YWFlNGY1OS0xMzA3MDUyMDg1
  JWT_SECRET: OGNmNTM2Njc0ZTE1MjEzMGQxNjI5MjUzOWRhNGIyOWUwMzVhZmJlMDFlMjc5YmJiZTllMjc0ZDcxODM4NTk0Zg==
  SPRING_DATASOURCE_URL_MASTER: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtbWFzdGVyLWRhdGFiYXNlOjU0MzIvS3VlbnRlQ08=
  SPRING_DATASOURCE_USERNAME_MASTER: bWFzdGVy
  SPRING_DATASOURCE_PASSWORD_MASTER: cm9vdA==
  SPRING_DATASOURCE_URL_SLAVE: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXMtcmVwbGljYS1kYXRhYmFzZTo1NDMyL0t1ZW50ZUNP
  SPRING_DATASOURCE_USERNAME_SLAVE: cmVwbGljYXRvcg==
  SPRING_DATASOURCE_PASSWORD_SLAVE: cm9vdA==
  MONGO_URI: bW9uZ29kYjovL2FkbWluOnNlY3JldEBtb25nby1kYXRhYmFzZToyNzAxNy9haWNoYXRkYj9hdXRoU291cmNlPWFkbWlu
  MONGO_USERNAME: YWRtaW4=
  MONGO_PASSWORD: c2VjcmV0
  MONGO_DATABASE: YWljaGF0ZGI=
  MONGO_COLLECTION: Y2hhdF9oaXN0b3J5
  OPENAI_KEY: c2stcHJvai1qSjNJbTJhTng3SndtYkdtYTR0N3Bzd09nMXRJNF9pVU9Ic2s4d3AwRS1uV3NsaTF4OGhMd2dYOHBWRkh4eEF5Qy1sTXpIWWNFMVQzQmxia0ZKbnlReWd6UHRteTVmeVlVMlAzQm5iMXNLdlFqVmZ2YXlQRWxTRTBxeTB0ckp4emxjbGdHeVVtVzE3N216Mk13Q0dpcUR6bGxwY0E=
  OPENAI_MODEL: Z3B0LTQuMQ==
  DEEPSEEK_BASE_URL: aHR0cHM6Ly9hcGkuZGVlcHNlZWsuY29t
  DEEPSEEK_KEY: c2stMTVjY2Y1ZWViNjE5NDIwYmEwMzE1YTgwMzQ1Y2I4NWM=
  DEEPSEEK_MODEL: ZGVlcHNlZWstcmVhc29uZXI=
  KUENTECO_APP_URL: a3VlbnRlY28tYXBwOjgwODA=

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-master-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-replica-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-database-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 512Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-master-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-master-database
  template:
    metadata:
      labels:
        app: postgres-master-database
    spec:
      containers:
      - name: postgres-master-database
        image: yefff/image-master-kuenteco:1.0.0
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-master-volume
          mountPath: /var/lib/postgresql/data
        envFrom:
        - secretRef:
            name: kuenteco-secret
      volumes:
      - name: postgres-master-volume
        persistentVolumeClaim:
          claimName: postgres-master-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-master-database
spec:
  type: ClusterIP
  selector:
    app: postgres-master-database
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-replica-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-replica-database
  template:
    metadata:
      labels:
        app: postgres-replica-database
    spec:
      containers:
      - name: postgres-replica-database
        image: yefff/image-slave-kuenteco:1.0.0
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-replica-volume
          mountPath: /var/lib/postgresql/data
        envFrom:
        - secretRef:
            name: kuenteco-secret
      volumes:
      - name: postgres-replica-volume
        persistentVolumeClaim:
          claimName: postgres-replica-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-replica-database
spec:
  type: ClusterIP
  selector:
    app: postgres-replica-database
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-database
  template:
    metadata:
      labels:
        app: mongo-database
    spec:
      containers:
      - name: mongo-database
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-database-volume
          mountPath: /var/lib/postgresql/data
        envFrom:
        - secretRef:
            name: kuenteco-secret
      volumes:
      - name: mongo-database-volume
        persistentVolumeClaim:
          claimName: mongo-database-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-database
spec:
  type: ClusterIP
  selector:
    app: mongo-database
  ports:
  - port: 27017
    targetPort: 27017
    protocol: TCP


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuenteco-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuenteco-app
  template:
    metadata:
      labels:
        app: kuenteco-app
    spec:
      containers:
      - name: kuenteco-app
        image: yefff/image-backend-kuenteco-app:1.0.1
        ports:
        - containerPort: 8080
        envFrom:
        - secretRef:
            name: kuenteco-secret
        volumeMounts:
        - name: dotenv-volume
          mountPath: /workspace/.env
          subPath: .env.docker
      volumes:
      - name: dotenv-volume
        configMap:
          name: kuenteco-env

---
apiVersion: v1
kind: Service
metadata:
  name: kuenteco-app
spec:
  type: NodePort
  selector:
    app: kuenteco-app
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    nodePort: 30080

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuenteco-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kuenteco-chat
  template:
    metadata:
      labels:
        app: kuenteco-chat
    spec:
      containers:
      - name: kuenteco-chat
        image: yefff/image-backend-kuenteco-chat:1.0.1
        ports:
        - containerPort: 7070
        envFrom:
        - secretRef:
            name: kuenteco-secret
        volumeMounts:
        - name: dotenv-volume
          mountPath: /workspace/.env
          subPath: .env.docker
      volumes:
      - name: dotenv-volume
        configMap:
          name: kuenteco-env

---
apiVersion: v1
kind: Service
metadata:
  name: kuenteco-chat
spec:
  type: NodePort
  selector:
    app: kuenteco-chat
  ports:
  - port: 7070
    targetPort: 7070
    protocol: TCP
    nodePort: 30070