package com.example.back_end.enums;

public enum ResponseType {
    SIMPLE_TEXT,
    CHART_DATA,
    DEBT_ANALYSIS,
    SPENDING_PATTERNS,
    FINANCIAL_HEALTH,
    EXPENSE_SUGGESTIONS,
    FINANCIAL_PROJECTION,
    BUDGET_COMPARISON,
    REPORT_DOWNLOAD
}
