spring:
  config:
    activate:
      on-profile: master
  datasource:
    url: ${SPRING_DATASOURCE_URL_MASTER}
    username: ${SPRING_DATASOURCE_USERNAME_MASTER}
    password: ${SPRING_DATASOURCE_PASSWORD_MASTER}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      idle-timeout: 20000
      connection-timeout: 60000  # Aumentado para dar más tiempo de conexión
      max-lifetime: 1800000
      initialization-fail-timeout: 60000  # Tiempo de espera antes de fallar
      validation-timeout: 5000
      leak-detection-threshold: 60000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    open-in-view: false

  flyway:
    enabled: false
    locations: classpath:db
    baseline-on-migrate: true
    out-of-order: false
    validate-on-migrate: true
    sql-migration-prefix: V
    sql-migration-separator: __
    sql-migration-suffixes: .sql
    schemas: public
    placeholders:
      application_user: ${SPRING_DATASOURCE_USERNAME_MASTER}

#logging:
#  level:
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.flywaydb: DEBUG