services:
#BASE DE DATOS POSTGRESQL MAESTRA
  postgres-master-database:
    image: yefff/image-master-kuenteco:1.1.1
    container_name: DatabaseMasterKuenteCOSub
    volumes:
      - postgres-master-data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    networks:
      - kuenteco-sub-network
    restart: unless-stopped

#BASE DE DATOS POSTGRESQL REPLICA
  postgres-replica-database:
    image: yefff/image-slave-kuenteco:1.1.1
    container_name: DatabaseSlaveKuenteCOSub
    volumes:
      - postgres-replica-data:/var/lib/postgresql/data
    ports:
      - "5430:5432"
    networks:
      - kuenteco-sub-network
    depends_on:
      postgres-master-database:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres-master-data:
  postgres-replica-data:

networks:
  kuenteco-sub-network:
    driver: bridge
