slave:
  config:
    activate:
      on-profile: slave
  datasource:
    url: ${SPRING_DATASOURCE_URL_SLAVE}
    username: ${SPRING_DATASOURCE_USERNAME_SLAVE}
    password: ${SPRING_DATASOURCE_PASSWORD_SLAVE}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      idle-timeout: 20000
      connection-timeout: 10000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE