slave:
  config:
    activate:
      on-profile: slave
  datasource:
    url: ${SPRING_DATASOURCE_URL_SLAVE}
    username: ${SPRING_DATASOURCE_USERNAME_SLAVE}
    password: ${SPRING_DATASOURCE_PASSWORD_SLAVE}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 50
      minimum-idle: 5
      idle-timeout: 20000
      connection-timeout: 10000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: none # Deshabilitamos DDL automático en el slave
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        connection:
          read_only: true

    # Deshabilitamos Flyway en el perfil esclavo
    flyway:
      enabled: false

#logging:
#  level:
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE