jwt:
  secret: ${JWT_SECRET}
  expiration: 86400

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      base-path: /
      exposure:
        include: "info,health"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        sliding-window-size: 50
        sliding-window-type: count_based
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 3s
        permitted-number-of-calls-in-half-open-state: 5
        register-health-indicator: true
        record-exceptions:
          - io.netty.handler.timeout.ReadTimeoutException
          - java.lang.RuntimeException
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
    instances:
      app-resilience-config:
        base-config: default

  ratelimiter:
    configs:
      default:
        limit-for-period: 100
        limit-refresh-period: 1s
        timeout-duration: 500ms
    instances:
      post-insert:
        base-config: default

server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 2KB
    mime-types: application/json,application/xml,text/html,text/plain,text/css,application/javascript
  tomcat:
    threads:
      max: 500
      min-spare: 50
    connection-timeout: 20000
  servlet:
    context-path: /api


spring:
  sendgrid:
    api-key: ${SENDGRID_API_KEY}
    email: ${EMAIL_SENDGRID}
    functions:
      verify-email: ${VERIFICATION_EMAIL}
      reset-password: ${RESET_PASSWORD}
  profiles:
    active: master,slave

logging:
  level:
    org.springframework.security: DEBUG
    org.kuenteco.backend: DEBUG
    com.zaxxer.hikari: DEBUG
    org.hibernate.SQL: DEBUG
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR

info:
  application:
    groupId: '@project.groupId@'
    artifactId: '@project.artifactId@'
    version: '@project.version@'